---
title: "Term paper"
subtitle: ""
author: "Rose Hörsting & Gina Reinhard"
date: "2025-03-15"
engine: knitr
bibliography: references.bib
format: 
  html:
    df-print: default
    toc: true
    toc-depth: 3
    fig-width: 10
    fig-height: 8
    number-sections: true
    embed-resources: true
link-citations: true
csl: "apa_7th.csl"
number-sections: true
---

# Introduction

-   rare construction: Only 5% of verbs in the French Treebank (FTB) are in the passive voice ( @da_cunha_lalternance_2020) vs. 9% in English for the same text type (@roland2007frequency).

# The French passive alternation of *être* and *se faire*

## Canonical passive with *être*

### Structure and meaning

-   Function of the passive construction (semantic focus):

-   Diathesis: Concept of the passive (passif long) as an inversion of the order/ syntactic function of the arguments (the subject argument and the object argument) in relation to the active construction. The object of the active "becomes" the subject in the passive. (Per default, in French the subject is coded at position 1 in the sentence)

-   The omission of the agent argument, called the *complément d'agent* (*par* or *de* phrase), is also possible. In this case, the construction is referred to as *passif court*, whereas the *passif long* explicitly includes the complément d'agent:

    *Language examples from our corpus*

    Approx. a quarter of all passive constructions in the French Treebank (FTB) are realised as passif long (@da_cunha_lalternance_2020), while in spoken French, the proportion is about 10% (source Hamma).

-   evtl.: passive vs. *construction moyenne en se* (*La porte a été ouverte* vs. *la porte s'est ouverte*) -\> In the passif court, the agent argument is still implicit (Quellen)

### XXXXXX

Several corpus studies on the active/passive alternation in French have shown that the choice between active and passive constructions is not purely syntactic, but that semantic and pragmatic factors also play a crucial role in determining whether a passive construction is favoured.

-   Subjects in passive sentences are preferably animate, definite, and pronominal. In the study by @da_cunha_lalternance_2020, animate, definite, and pronominal arguments that function as the objects in active sentences were more frequently found in the passive (and vice versa). -\> prominence / informational structure as significant factor. (And: constituent length, shorter constituents are preferred in subject position and favour the passive voice)

-   Animacy has been shown to play an important role in the active/passive alternation in French.

-   Interestingly, gender also seems to play a role in the active/passive alternation. In @da_cunha_lalternance_2020 the passif court model showed a significant effect of grammatical gender: a feminine agent increased the likelihood of the the passive.

-   Surprisingly, number also had an effect: a plural arguments favoured the passive in all models. (+ Relativsätze & Priming als signifikante Faktoren) @da_cunha_lalternance_2020

## *se faire* passive

### Historical background <!-- not sure if relevant -->

@bellec_grammaticalisation_2015 and @bellec_quand_2014 date the se faire + INF passive construction (PSF) to the middle of the 20th century and call it a "modern" construction that has since experienced a rapid increase in popularity. She describes a process of grammaticalisation and reanalysis for the PSF during/through which “se” has lost its reflexive meaning and “faire” has become an auxiliary. In merging, they form a “semi-auxiliary” and obtain a passive interpretation, while the causative meaning is lost (désémantisation). However, @bellec_construction_2014 claims that the causative reading did not disappear but instead coexists with the passive reading (debated, see below).

-   In contrast, @raineri_analyse_2010 [280-305] based on corpus data: sees origin much earlier, exists since origin of Middle French (14-17th century); NOT derived from causative reading, increased productivity from 19th century onward

### Structure and meaning

The construction consists of the pronoun "se", the conjugated form of the verb "faire" and an infinitive (INF). According to @labelle_anticausativizing_2013\[235\] the construction is "formally causative, but semantically passive". The peculiarity of the construction has led scholars to wonder: "how can a passive-like construction arise from a combination of a causative and a reflexive marker, where no marking of the passive function is apparent?" (@koenig_semantic_1992\[145\]).

Sentences including this construction can have either/both a passive and/or a causative sense:

**Language examples**

@koenig_semantic_1992\[143\]:\
Jean s'est fait tuer hier.\
Jean was killed yesterday. (passive)\
Jean made somebody kill him yesterday. (causative)

Crucially, passive se faire and causative se faire are structurally identical and differ only in their semantics. As @labelle_anticausativizing_2013\[236\] explains, the ambiguity is resolved by "the lexical items involved". In the causative reading, "se" is understood to have reflexive meaning and "faire" is understood to have causative meaning. In contrast, if interpreted as a passive, the meanings of "se" and "faire" are not transparent. Thus, the subject does not necessarily cause the event and is not necessarily responsible (@koenig_semantic_1992\[143\]: "any notion of causation is absent"). Sometimes both readings are possible and the ambiguity cannot be resolved @koenig_semantic_1992\[144\], for example when cognition and perception verbs are involved @bellec_construction_2014\[206, 207\].

<!-- @kupferman_construction_1995 reasons that the PSF is a real, fully adequate passive construction, equivalent to the être passive. Others have different opinions... -->

From the active to the se faire passive:

@labelle_anticausativizing_2013 [23] suggests that the passive meaning and (affected reading) is obtained through a syntactic mechanism that involves binding the empty NP-object position of the embedded verb to the subject through the reflexive particle "se".

<!-- In the se faire passive, the embedded verb (i.e., the infinitive after faire) has an empty NP-object position since only the subject is realised. The reflexive clitic "se" binds the empty object position of the embedded verb. Therefore, "se" connects the (missing) object-NP and the surface subject (coindexation). In contrast to the être passive, the object does not become the new subject but is connected to the subject by "se". The subject is interpreted as affected because it is linked to the missing object of the embedded verb (which would be affected in the active sentence but is absent on the surface in se faire). For this to work, the embedded verb needs an agent as a subject (because otherwise, the missing object would not be affected). -->

### Debate of the construction's passive-status (vs. causative)

The above described stance taken by @bellec_construction_2014, @labelle_anticausativizing_2013, @koenig_semantic_1992 and @kupferman_construction_1995 that the PSF is a full-fledged passive construction is by no means undisputed. The opposing view - that the construction is a subtype of the causative - is also widely represented in the literature.

As @raineri_analyse_2010 describes, there are mainly two opposing views in the literature:

-   On the one hand: se faire + inf does not have a inherent passive reading; the fact that the construction is understood as passive depends in verb semantics and pragmatics @tasmowski-de_ryck_causatif_1987, @gaatone_desagreable_1983, @sveberg_se_2012

-   on the other hand: assume that the passive interpration of se faire + inf is a real. independent passive @labelle_anticausativizing_2013, @kupferman_construction_1995, Martin...

-   also: possibility of multitude of reading or of a continuum between causative and passive (Kokutani, Hobak Haff @raineri_analyse_2010 \[89\], later accepted by @raineri_analyse_2010 [154-166]

The question whether the referent of the subject in the se faire construction holds any responsibility is central in the debate of the construction's passive-status. As @labelle_anticausativizing_2013 [15] explains: @gaatone_desagreable_1983 as well as @tasmowski-de_ryck_causatif_1987 center their argumentation that the se faire passive is only a "subtype"/ a weak reading of the causative around the notion that the subject of the se faire construction "is always, even unconsciously, responsible for the occurrence of the embedded event." @gaatone_desagreable_1983 claims that inanimate subjects are not possible with the se faire passive reading since they cannot be responsible. @labelle_anticausativizing_2013 argues against that by providing examples of the passive with inanimate subjects. While @kupferman_construction_1995 sees causative and passive readings as homonymes with fundamentally different semantics and therefore claims that the se faire construction "deserves" to be viewed as a real passive, @sveberg_se_2012 thinks that the se faire construction is always causative and that constructions with inanimate subjects can still be causative if the subject is personified.

@raineri_analyse_2010 comes to the conclusion that despite its productivity as a passive construction, the PFS' status as a passive is problematic because it neither fits into two homonymes nor does it function a single weakly determined causative.

According to @bellec_construction_2014, the se faire passive has been grammaticalised into a semi-auxiliary where the meaning of its components are not transparent anymore and there is thus no reason for a causative reading. @bellec_construction_2014\[207\] defines the following three criteria for a causative reading, by which the causative and the passive interpretation are distinguished:

-   In the causative, the subject referent is agentive and has both the role of causer/ initator and patient/ experiencer. In the passive, the subject referent has only the role of the patient.
-   In the causative reading, the particle “se” functions has a reflexive meaning. In the passive reading, “se” is not reflexive.
-   In the causative reading, “faire” has transparent causative meaning. In the passive reading, “faire” has no inherent meaning and is not causative.

This debate has been central in the investigations of the se faire + INF constructions and cannot be left aside in our study as it deals with the question whether the construction we aim to investigate actually exists.

However, even though the status of the PSF has been subject to disagreements and discussion, the literature clearly shows that there is a passive reading related to this construction. This is independent from whether the passive sense emerges from within the construction or out of the components it occurs with. By comparing PSF and PE constructions, we may shed some light on this debate from a corpuslinguistics' standpoint by examining which factors contribute to the choice between the two passives. <!-- (-> exclude causative readings?). Can our findings contribute to the debate of whether se faire deserves passive-status? If not: no need to spell out the debate in detail. -->

## *être* vs. *se faire*: Competition or complementation? - Defining the variable context

The passive constructions of se faire and être are not always interchangeable: As described above, the canonical passive with être requires a direct object in the active equivalent becoming the new subject, @koenig_semantic_1992\[144\], @washio_when_1993, @labelle_anticausativizing_2013\[16\]. Thus, for reflexive and ditransitive verbs, the être passive is not available and does not compete with se faire. These constructions will be excluded and only transitive verbs will be investigated.

-   se faire passive has evolved to be used in situations without a causer (passive reading) @bellec_construction_2014
-   figurative, "besoin d’expressivité and extravagance" instead of "used up" canonical passive @bellec_construction_2014 [206]
-   while some scholars speak of semantic differences between the canonical être passive and the se faire passive, @kupferman_construction_1995 sees them as semantically synonymous -\> therefore: competition
-   how much is it used today (according to authors/ background literature) and in which settings
    -   se faire less formal, more figurative and emotional, used to build the passive with indirect object as the agent & to express passivity in dynamic/ ongoing processes, more spoken
    -   etre passive more “neutral”, more formal, more written
-   strategy for @raineri_analyse_2010 to exclude causative constructions: keep only utterances for which the etre V paraphrase seems more natural than a causative paraphrase; also excludes lexicalised idioms because they convey a more complex meaning than paraphrase in etre

### Maybe: Comparison to similar alternations in other languages

-   English @bohmann_large-scale_2023, East Asian languages @washio_when_1993 and @guan_multifactorial_2024 , Swedish @cuypere_corpus-based_2014
-   se faire passive "typologically marked", comparison to other Romance languages @koenig_semantic_1992 \[145\]; similar constructions exist in other Romance languages but passive reading only allowed in French @labelle_anticausativizing_2013 [236]

# Data and Methods

## Data Collection

## Logistic Regression

Variables, Hypotheses, Preference constraints

### Subject responsibility

Subject responsibility in the se faire passive widely debated and is central for the debate on whether the passive reading of se faire is a subtype of the causative reading or its own instance (see above; @sveberg_se_2012, @bellec_construction_2014 \[212-213\]). In @raineri_analyse_2010 [95]'s view, the idea that the PSF expresses subject responsibility is the "most common hypothesis" ("l'hypothèse la plus répandue") in the literature. However, it is not "universally accepted" @raineri_analyse_2010 \[98\] as there are counter-examples @kupferman_construction_1995 [59].

In line with their argumentation that the passive reading of se faire + INF is a type of causative, @gaatone_desagreable_1983 and @tasmowski-de_ryck_causatif_1987 state that the subject referent of the se faire passive is always a causer that is always responsible to some degree. In contrast, @kupferman_construction_1995 [98, 99] claims that PSF has inherent passive meaning and the subject is only occasionally interpreted as partially responsible.

@gaatone_desagreable_1983 \[164\] distinguishes between an "active patient" in se faire construction and a "passive patient" in the être passive.) @raineri_analyse_2010 [96]. However, @labelle_anticausativizing_2013 claims that there is no causer in passive se faire → subject is not necessarily responsible (also @washio_when_1993), Martin 2002: subject intentionality is not necessary but dynamicity is @raineri_analyse_2010 [90]. No consensus regarding the "causer"-degree/ status of the subject but @raineri_analyse_2010 reflects that all analysises have in common that the subject is always in some way connected to the event. (difference: affectedness/ responsibility/ intentionality)

-   **Animacy** TAGGING: continuum? inanimate vs. animate? (@bohmann_large-scale_2023 added: ”body parts”, “other”; @hundt_be-_2024 added: “human”)

    As implied in the debate of subject responsibility, subjects of se faire passive constructions are predominantly active participants of the described action. PSF is common with animate subjects since inanimate subjects are rarley affected and even less frequently responsible. Indeed, this is reflected in both corpus studies (@novakova_construction_2009) and experimental studies (@koenig_semantic_1992\[151, 153\]): In a survey, French Native speakers rated the acceptability of animate subjects with the se faire passive significantly higher than with inanimate subjects. Inanimate subject were only allowed by some speakers when the subject "affects a relevant animate entitity" (@koenig_semantic_1992 [151, 153]. The positive correlation of animate subjects and PSF is relatively indisputed: Subject animacy preponderance for the se faire passive seems to be one of the few aspects in which scholars agree (@raineri_analyse_2010 [92]).

    Although it has also been claimed that the "subject of se faire passive \[is\] required to be animate", there are some examples for PSF occurring with inanimate subjects: (@novakova_construction_2009 [4]: a little bit less than ?% in her corpus; examples; and Kokutani (@raineri_analyse_2010 [92]\] (and in idioms, @labelle_anticausativizing_2013 and personifications, @sveberg_se_2012)).

    The preference of the se faire passive of animate over inanimate subjects is parallel to the English get passive @hundt_be-_2024, although @raineri_analyse_2010 \[92\] says that the get passive allows more inanimate subjects than the se faire passive. According to @bohmann_large-scale_2023 [43], the get passive has become more likely with inanimate subjects over time which may signify a lessening of subject responsibility. @raineri_analyse_2010 brings up the possibility that a similar process of grammaticalisation may be happening in French.

-   Interactions: @raineri_analyse_2010 [94] suspects that the PSF's animacy (almost-) constraint restricts verb selection and provides an explanation for the construction's incompatibility with certain verbs (not all verbs can occur with animate subjects).

-   **Agent PP** (par-phrase, Complément d'agent)

    -   @hundt_be-_2024, the “by-phrase openly assigns responsibility” to an external agent
    -   @bohmann_large-scale_2023: by-phrase “partially mitigate subject responsibility”, expected to favour be-passive (finding: more in the early data than now)
    -   → par-phrase less likely for se faire than for etre passive?
    -   @kupferman_construction_1995: agentivity requirement for agents denoted by par-phrase; for PSF par-phrase with abstract cause not possible (in contrast to être passive?)

-   **Modal verbs**: such as "devoir", "savoir", "pouvoir", "falloir", "vouloir" very frequent with se faire passive @novakova_construction_2009 \[9\] (in @raineri_analyse_2010 [97], reason: they denote "control" to the subject

**Hypothesis:**

Animate subjects will favour the *se faire* passive, while inanimate subjects will favour the canonical *être* passive. PSF strongly favours animate subjects and disfavours inanimate subjects.

Further, we hypothesize that the presence of an agent PP ("Complément d'agent") prefers the canonical être passive over the se faire passive (because it assigns responsibility to an external agent that is not the subject).

### Aspectuality (Aspect/"Aktionsart")

The overall consensus in the literature is that aspect marks progressivity grammatically and Aktionsart semantically/ lexically. However, this clear cut distinction of Aspect and Aktionart has been doubted, and some theories see Aktionart und Aspect as two instantiations of Aspectuality (Quelle, not focus).

-   **Telicity:**
    -   According to @bellec_construction_2014 [209], the être passive is likely to describe a result/ mark an endpoint of an action, while the se faire passive is used for actions in process. This could be reflected in the telicity of the verb, where telic verbs favour the être passive and atelic verbs favour the se faire passive.
    -   se faire passive preferred for verbs that are in their nature ongoing (e.g. perception verbs) @bellec_construction_2014 [209]
    -   @raineri_analyse_2010 [365] sees the "type of process denoted by the verb" as a "necessary condition", inchoative/ durative aspect: "get passive and se faire passive focus on onset of the process that affects the subject referent, whereas be and etre passive present the process in its entirety, without offering an internal perspective."
-   **Periphrase constructions**: According to @spang-hanssen_quelques_1967 \[141\] and @novakova_construction_2009, periphrases that denote progressivity such as “être en train de + INF”, “venir de + INF” and “aller + INF” occur more naturally with the se faire passive than with the être passive. This is due to the dynamicity that the se faire passive entails (Quelle) compared to the more stative être passive. (also: @bellec_construction_2014; @keenan_passive_2007 [341], @raineri_analyse_2010 [91]
-   **Verbs**: se faire passive works well with dynamic verbs but not with stative verbs @raineri_analyse_2010 \[90\], @kupferman_construction_1995 [67] (but exceptions provided by @novakova_construction_2009); Martin 2002, @raineri_analyse_2010 [100-103] volitional verbs fit well with PSF because they involve an action that leads to a mental state change while non-volitional verbs do not
-   **Aspect** tagging @hundt_be-_2024 : simple, perfect, progressive; @bohmann_large-scale_2023 [39]: "Form of auxiliary verb: present, preterite, perfect, infinitive, -ing"
-   **Tense:** Descriptions of future events are more likely to focus on the start and process of an event or an action than on its endpoint (@bellec_construction_2014 [210]) Therefore, it seems likely that future tense will favour the se faire passive over the être passive. Regarding past tense, the être passive will probably be more popular than se faire for constructions in the passé composé (passé composé also used with se faire if speaker wants to emphasize a process, @bellec_construction_2014). In contrast, the se faire passive may be preferred if the action is described in the imparfait (only a guess).

**Hypothesis:** Perception verbs, "dynamic" verbs more often with se faire passiv; Interaction of verb type with subject animacy??

### Adversativity/ Non-neutrality

The factor of "Adversativity/ Non-neutrality" is reflected in the semantics of the verb and captures (negative) consequences that the described action has on the subject. It has been found to be relevant to the choice between the be and get passive (@hundt_be-_2024 [89, 96-97]). It is tagged on the verb as binary by @hundt_be-_2024 : adversative, non-adversative/ neutral.

The interaction of subject animacy and verb adversativity may show affectedness of the subject: Consequences of actions, expressed by adversative verbs, affect animate subjects more than inanimate subjects. Therefore, adversativity and animacy may co-occur frequently.

-   @gaatone_desagreable_1983 in @raineri_analyse_2010 [103]: se faire passive has a sense "désagreable" (unpleasant); subject affected by unpleasant event -\> according to him unpleasant events contradict notion of subject responsibility because subject would not willingly bring the unpleasant event onto themselves) (therefore argument for "primacy of causative reading); also @spang-hanssen_quelques_1967, @raineri_analyse_2010 parallels to English get passive

-   @novakova_construction_2009 : 30% of verbs in PSF denote unpleasant events and 5% denote plesant events (in @raineri_analyse_2010 [194])

-   @kupferman_construction_1995 [77]: Although he rejects that the "unpleasant" sense is a characteristic of se faire (also used with positive), he agrees that it is more commonly used for unpleasant contexts ("has tended to specialize in unpleasant roles" (compared to être))

<!-- -->

-   @bohmann_large-scale_2023 [38, 43] Sentiment values of verb participles extracted from SentiWordNet: positivity, negativity, objectivity scores; reversed if sentence is negated
    -   adversativity and non-neutrality hypothesis both expect get passive to favour verbs with negative scores; but only non-neutrality hypothesis predicts get passive to correlate positively with positive emotion scores
-   Verb clusters, verb semantics @bohmann_large-scale_2023 [51-52]: 21 levels

### Mode

spoken vs. written

-   se faire passive favoured in spoken French; être passive favoured in written French @raineri_analyse_2010

### (Maybe: Register)

Text genre, formal vs. informal

-   se faire passive more likely in informal settings, être passive more likely in formal settings

### Morphosyntactic features

Negation, subject person, subject number, subject gender

@bohmann_large-scale_2023 [39]: get passive disfavoured in complex constructions (e.g. negation); parallel in French?

## (Maybe: Memory based learning)

# Results

# Discussion

# Conclusion/Outlook

# References
